name: habitatgn
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.7.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cloud_firestore: ^5.0.2
  firebase_ui_auth: ^1.15.0
  firebase_core: ^3.1.1
  flutter_facebook_auth: ^7.0.1
  firebase_auth: ^5.1.1
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  flutter_spinkit: ^5.2.1
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  fluttertoast: ^8.2.14
  connectivity_plus: ^6.1.0
  firebase_messaging: ^15.0.4
  location: ^7.0.0
  geolocator: ^13.0.1
  webview_flutter: ^4.8.0
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.3.2
  share_plus: ^10.1.1
  flutter_localization: ^0.3.3
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/locations/
